name: Upload to Percy

on:
  workflow_run:
    workflows: ['Build for Percy']
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: 'Download Storybook Artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var fs = require('fs');
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.find((artifact) => {
              return artifact.name == "storybook-output"
            });
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            fs.writeFileSync('${{github.workspace}}/storyook-static.zip', Buffer.from(download.data));
      - run: unzip storybook-static.zip
      - run: npx percy-storybook
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
